"""Changed nullable for user language

Revision ID: 8876e798292a
Revises: aeb71fd07531
Create Date: 2023-11-15 12:46:17.142317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8876e798292a'
down_revision: Union[str, None] = 'aeb71fd07531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               server_default='en')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###
