"""Adding Language table

Revision ID: 8a228c6a56dc
Revises: 851f018fdfab
Create Date: 2023-11-15 12:59:53.532613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a228c6a56dc'
down_revision: Union[str, None] = '851f018fdfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('short_name', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('messages', 'language')
    op.drop_column('users', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=8), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('language', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.drop_table('languages')
    # ### end Alembic commands ###
