"""Database creation

Revision ID: 8ca0f0a4032f
Revises: 
Create Date: 2023-10-26 21:36:08.068804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca0f0a4032f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.Column('base_url', sa.String(), nullable=False),
                    sa.Column('activated', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('blocked', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(length=150), nullable=False),
                    sa.Column('service_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('service_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(length=600), nullable=False),
                    sa.Column('url', sa.String(length=50), nullable=False),
                    sa.Column('themes', sa.String(length=50), nullable=False),
                    sa.Column('price', sa.String(length=50), nullable=False),
                    sa.Column('limit_time', sa.String(length=50), nullable=False),
                    sa.Column('publish_date', sa.String(length=50), nullable=False),
                    sa.Column('author', sa.String(length=50), nullable=False),
                    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_views',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('task_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('subscription_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscriptions')
    op.drop_table('task_views')
    op.drop_table('tasks')
    op.drop_table('subscriptions')
    op.drop_table('users')
    op.drop_table('services')
    # ### end Alembic commands ###
