"""Adding language links

Revision ID: a14e19b4772f
Revises: 8a228c6a56dc
Create Date: 2023-11-15 13:03:01.335122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14e19b4772f'
down_revision: Union[str, None] = '8a228c6a56dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('language_id', sa.BIGINT(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'messages', 'languages', ['language_id'], ['id'])
    op.add_column('users', sa.Column('language_id', sa.BIGINT(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'users', 'languages', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'language_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'language_id')
    # ### end Alembic commands ###
