"""Adding boolean parameters to user model

Revision ID: aeb71fd07531
Revises: d9237bb301b0
Create Date: 2023-11-15 12:42:55.608391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb71fd07531'
down_revision: Union[str, None] = 'd9237bb301b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
    op.drop_column('users', 'blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###
