"""Adding multilanguage system

Revision ID: d9237bb301b0
Revises: 07123387ce3c
Create Date: 2023-11-14 23:15:03.440209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9237bb301b0'
down_revision: Union[str, None] = '07123387ce3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('original_id', sa.BIGINT(), nullable=False),
    sa.Column('last_usage', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['original_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('language', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_table('messages')
    # ### end Alembic commands ###
